### ISSUE TITLE
Strip timestamps off buffer lines

### ISSUE THREAD

**Issue by rburchell** [rburchell/irssi-relay#1]
It's not really very useful to have both irssi's timestamp and the client-side timestamp attached. It would be nice to be able to strip off timestamps from the buffer lines.

**Comment by aquanight** [comment]
Timestamps can now be removed via /set ipw_strip_prefix which is a perl regex. The default value will be estimated off of /set timestamp_format, but it can be changed to anything really (and you may need to if you have anything extra in /format timestamp). There's an implicit ^ anchor so the regex doesn't need to include it and also it will remove any leftover leading whitespace.

If you later edit /set timestamp_format, you'll need to manually change your ipw_strip_prefix to match.

**Comment by rburchell** [comment]
Confirmed!
