### ISSUE TITLE
Investigate the display of CTCP ACTION plus prefix stripping.

### ISSUE THREAD

**Issue by rburchell** [rburchell/irssi-relay#11]
3e65e2abb96e7b1352a1a30c96ae7e918880eb5d introduced support for stripping of prefixes off lines. This is good, but CTCP ACTION (/me) now look visually the same as regular messages.

Perhaps we should be bolting on some additional metadata? Maybe prefix handling is a bit wrong?

**Comment by aquanight** [comment]
We now have prefix stripping for actions, ctcps, notices, and most other events that is consistent with weechat presentation. I.e. nick is not moved before the separator but the "*" marker is.
