### ISSUE TITLE
Weechat android fails with irssi-relay

### ISSUE THREAD

**Issue by Foxboron** [rburchell/irssi-relay#15]
It connected during the day today, but i can only see JOIN/PARTS/QUITS but no PRIVMSG. I can't send anything either.

I'm not well versed with perl, so if anyone have any tips on how to track this bug it would be great.

**Comment by rburchell** [comment]
First step would be to make sure that the message data is actually being intercepted and sent. There's a mechanism for debug logging (logmsg), the contents of which go to file, which is set up here:

https://github.com/rburchell/irssi-relay/blob/master/weechat-relay.pl#L150

The buffer contents should all be handled more or less the same way, so I can't say offhand why you wouldn't see only one type of message. I can't offer much easy advice on that other than that you will likely have to look at what requests the client is making (either in source or through debug logging), and then look at the structure documented here:

https://github.com/rburchell/irssi-relay/blob/master/weechat-relay.pl#L626

... and add logging as appropriate to figure out if the correct data is being sent to the requests in question.

**Comment by Foxboron** [comment]
This somehow seems resolved now. Did nothing.

**Comment by rburchell** [comment]
My favorite type of issue. Hopefully it was all a dream, take a look at the above if you want to take a look at it in the future :)

**Comment by Foxboron** [comment]
I think it fails a little if multiple clients connect. Was trying both glowing bear and weechat. But that probably deserves a new issue if it is the case.
